language: ruby
rvm: 2.3.1
install:
  - gem uninstall bundler
  - gem install -v 1.10.6 bundler --no-rdoc --no-ri
  - bundle _1.10.6_ install --path vendor/bundle
before_script:
  - export LANG=en_US.UTF-8
script: bundle exec nanoc compile
env:
  global:
    - "FTP_USER=admmin"
    - "FTP_PASSWORD=nemamnistapametno"
after_success:
    "curl --ftp-create-dirs -T output -u $FTP_USER:$FTP_PASSWORD ftp://188.93.125.70:22/var/data/wordpress/test"
